version: '3.8'
services:
  nest_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - app-network
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prisma
    ports:
      - '5432:5432'
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: '10m'
        max-file: '3'
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data: